# This is the Config file for ArticAntiVPN.
#
# Remember to join my Discord server if you need help:
# https://discord.nookure.com/
#
# General configuration for the plugin.
#
Config:
  prefix: '&c&lAnti&f&lVPN &8&l»&r '
  # Enable or disable the debug mode.
  # If enabled, the plugin will send more information about the plugin status.
  debug: true
  # Cache max size.
  cacheMaxSize: 1000
# Configuration for the VPN database.
Database:
  # The type of database you want to use, you can choose between SQLite or MySQL.
  # The MySQL driver also works with MariaDB
  type: 'SQLite'
  # Your database host IP address.
  host: '127.0.0.1'
  # Your database host connection port. Default for MariaDB and MySQL is 3306.
  port: 3306
  # Name of your database. A database server can contain multiple databases.
  database: 'articantivpn'
  # Your database host username.
  user: 'root'
  # Your database host password.
  password: ''
# Messages for the plugin
Message:
  alerts:
    # Message when a player joins with a VPN
    # to the console and all players with
    # the permission articantivpn.alerts.
    # Available placeholders:
    # ↳ {prefix} is the prefix of the plugin.
    # ↳ {player} is the name of the player.
    # ↳ {ip} is the IP of the player.
    # ↳ {country} is the country of the IP.
    # ↳ {countryCode} is the city of the IP.
    # ↳ {city} is the city of the IP.
    # ↳ {isp} is the ISP of the IP.
    vpnDetected: '{prefix} &c{player} &fjoined with a &cVPN&f! &8(&c{ip}&8) &8(&c{country}&8, &c{city}&8, &c{isp}&8)'
  # Kick message for the player.
  kickMessages:
    # Message when the player is kicked for using a VPN.
    # ↳ {prefix} is the prefix of the plugin.
    # ↳ {ip} is the IP of the player.
    # ↳ {country} is the country of the IP.
    # ↳ {countryCode} is the city of the IP.
    # ↳ {city} is the city of the IP.
    # ↳ {isp} is the ISP of the IP.
    vpnDetected: |
      &c&lAnti&f&lVPN
      &c&lVPN Detected!
      
      &fIf you think this is a mistake
      please contact the server staff.
      
      &chttps://discord.nookure.com/
Webhook:
  # Enable or disable the webhook.
  # If enabled, the plugin will send a message
  # to the webhook when a player joins with a VPN.
  enabled: false
  # The URL of the webhook.
  url: 'https://discord.com/api/webhooks/webhook-url'
  # The username of the webhook.
  username: 'ArticAntiVPN'
  # The avatar of the webhook.
  avatar: 'https://docs.nookure.com/img/logo.png'
  # Embed settings for the webhook.
  embed:
    # Embed title.
    title: 'ArticAntiVPN'
    # Embed description.
    description: 'A player joined with a VPN!'
    # Embed color. You have to use HEX color codes.
    color: "#FF6B6B"
    # Embed fields.
    # Available placeholders:
    # ↳ {prefix} is the prefix of the plugin.
    # ↳ {player} is the name of the player.
    # ↳ {ip} is the IP of the player.
    # ↳ {country} is the country of the IP.
    # ↳ {countryCode} is the city of the IP.
    # ↳ {city} is the city of the IP.
    # ↳ {isp} is the ISP of the IP.
    fields:
      name:
        name: 'Player'
        value: '{player}'
        inline: true
      ip:
        name: 'IP'
        value: '{ip}'
        inline: true
      isp:
        name: 'ISP'
        value: '{isp}'
        inline: true
      country:
        name: 'Country'
        value: '{country}'
        inline: true
    # Embed footer.
    footer:
      # Embed footer text.
      text: 'ArticAntiVPN'
      # Embed footer icon.
      icon: 'https://docs.nookure.com/img/logo.png'
    # Embed thumbnail.
    thumbnail: 'https://mc-heads.net/avatar/%player%/'